name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn test
      - name: Generate JaCoCo report
        run: mvn jacoco:report
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_report
          path: target/site/jacoco/jacoco.xml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/*.jar
